inventory/urls.py
"""URL Routing for Plastic Inventory"""

from django.conf.urls import url 

from . import views

urlpatterns = [
    # Plastic Home Page/Main App Home Page
    url(r'^$', views.index, name='plastic-home'),
    # Add a new plastic
    url(r'^add/$', views.add, name='add'),
    # View/modify specific plastic
    url(r'^detail/(?P<id>[0-9]+)/$', views.detail),
    # Delete specific plastic
    url(r'^delete/(?P<id>[0-9]+)/$', views.delete, name='delete'),
    # Logs Home/List all Logs
    url(r'^logs/$', views.logIndex, name='log-home'),
    # Add new log
    url(r'^logs/add/$', views.addLog, name='add-log'),
    # Delete specific log
    url(r'^logs/delete/(?P<id>[0-9]+)/$', views.deleteLog, name='delete-log'),
]

quality/urls.py
"""URL Routing for Quality App"""

from django.conf.urls import url

from . import views

urlpatterns = [
    # Quality home page
    url(r'^$', views.index, name='quality-home'),
    url(r'^rma/$', views.rma_index, name='rma-home'),
    url(r'^rma/delete/(?P<pk>[0-9]+)/$', views.rma_delete, name='rma-delete'),
]

website/urls.py
"""Basic url routing for the entire portal"""

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html')),   # Main portal page
    url(r'^admin/', admin.site.urls),                               # Admin site
    url(r'^inventory/', include('inventory.urls')),                  # Inventory App
    url(r'^quality/', include('quality.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)   # Include uploaded media files

inventory/models.py
"""Inventory Database Models"""

from django.db import models
from django.core.exceptions import ValidationError

class Plastic(models.Model):
    """Represents a type of plastic used for injection molding."""

    number = models.CharField("plastic part number",max_length=30)
    description = models.CharField(max_length=50)
    quantity = models.DecimalField(max_digits=10, decimal_places=1)
    purchase_date = models.DateField("last date of purchase",
                                         blank=True, null=True)
    vendor = models.CharField(max_length=30, blank=True)
    purchase_price = models.DecimalField("last purchase price", 
            max_digits=10, decimal_places=2, blank=True, null=True)
    order_threshhold = models.DecimalField(max_digits=10,
                                             decimal_places=1)

    def needs_ordered(self):
        """Returns true if quantity is below order threshold"""
        return self.quantity < self.order_threshhold

    def __str__(self):
        return self.number

    def get_absolute_url(self):
        return "/inventory/detail/{}/".format(str(self.id))

class Log(models.Model):
    """A log is a record of the changes to a plastic qty"""
    plastic = models.ForeignKey('Plastic', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    new_value = models.DecimalField("new value", max_digits=10, decimal_places=2)
    notes = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return str(self.timestamp)

    class Meta:
        ordering = ['-timestamp']

inventory/forms.py
"""Model-based forms and their customization"""

from django.forms import ModelForm
from .models import Plastic, Log

class PlasticForm(ModelForm):

    class Meta:
        model = Plastic
        exclude = []

class LogForm(ModelForm):

	class Meta:
		model = Log
		exclude = ['timestamp']

inventory/views.py
"""View controller for the inventory application"""

# Imports
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from .models import Log, Plastic
from .forms import LogForm, PlasticForm
from django.db.models import ProtectedError
from django.contrib import messages

### Plastics Views

# Home Page
def index(request):
    search_value = request.GET.get("search")
    if search_value:
        plastics = Plastic.objects.filter(number__contains=search_value)
    else:
        plastics = Plastic.objects.all().order_by('number')
    context = {"plastics": plastics,
                "search": search_value or ""}
    return render(request, "inventory/index.html", context)

# Add new plastic
def add(request):
    # If user has submitted form
    if request.method == "POST":
        # Check it for validity.  If Valid
        form = PlasticForm(request.POST)
        if form.is_valid():
            # Create new plastic and log the creation
            newPlastic = form.save()
            firstLog = Log(plastic=newPlastic, new_value=newPlastic.quantity, notes="Added new plastic")
            try:
                firstLog.save()
            except ValidationError as e:
                messages.success(request, "Plastic created.  Log couldn't be created.")
            return HttpResponseRedirect('/inventory/')
        else:
            raise Http404("There was a problem adding the plastic.")
    else:
    # Otherwise, show the blank form
        form = PlasticForm()
        return render(request, "inventory/plastic-form.html",
                        {"form": form})

# View the details of plastics, and update if need be
def detail(request, id):
    plastic = get_object_or_404(Plastic, pk=id)
    # If user submitted form
    if request.method == "POST":
        form = PlasticForm(request.POST, instance=plastic)
        # Check it for validity
        if form.is_valid():
            # If user changed the qty
            qty = form.cleaned_data['quantity']
            if qty != plastic.quantity:
                modLog = Log(plastic=plastic, new_value=qty)
                modLog.save()
            # log the change, then save
            form.save()
            return HttpResponseRedirect('/inventory/')
        else:
            raise Http404("Plastic couldn't be updated.")
    else:
    # Otherwise show the form with the current record
        form = PlasticForm(instance=plastic)
        return render(request, "inventory/plastic-form.html",
                                    {"form": form,
                                    "plastic": plastic})

# Delete a plastic
def delete(request, id):
    plastic = get_object_or_404(Plastic, pk=id)
    try:
        plastic.delete()
    except ProtectedError:
        messages.error(request, 'Cannot delete this plastic.  A log exists that references this plastic.')
    return HttpResponseRedirect("/inventory/")

### Log Views

# Add new log 
def addLog(request):
    # If form has been submitted
    if request.method == "POST":
        # Make sure it is valid.  if so
        form = LogForm(request.POST)
        if form.is_valid():
            # Make the new log, but, assuming most logs will be plastic use,
            # ensure logs can only subtract plastic
            newLog = form.save(commit=False)
            newLog.plastic.quantity = newLog.new_value
            newLog.plastic.save()
            newLog.save()
            return HttpResponseRedirect(newLog.plastic.get_absolute_url())
        else:
            return render(request, "inventory/log-form.html",
                        {"form": form})
    else:

    # Otherwise, show the blank log form
        form = LogForm()
        return render(request, "inventory/log-form.html",
                                {"form": form})

# Log home page, shows all logs
def logIndex(request, plastic=None):
    # Allow for filter by plastic
    if plastic:
        logs = Log.objects.filter(plastic=plastic).order_by('-timestamp')
    else:
        logs = Log.objects.all().order_by('-timestamp')
    return render(request, "inventory/log-home.html",
                                {"logs": logs,
                                "plastic": plastic})

# Delete a specific log
def deleteLog(request, id):
    log = get_object_or_404(Log, pk=id)
    try:
        log.delete()
    except ProtectedError:
        messages.error("Could not delete this log.  It may have children that depend on it.")
    target = request.META.get('HTTP_REFERER', '/inventory/')
    return HttpResponseRedirect(target)

inventory/templates/inventory/base.html
{% load staticfiles helpers %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}PQ Inventory{% endblock %}</title>
    {% block head %}
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

      <link rel="stylesheet" href="{% static 'inventory/css/custom.css' %}">
    {% endblock %}
  </head>

  <body>
    <div class="container">
      {% include 'inventory/alerts.html' %}
      {% block body %}
      {% endblock %}
      {% block scripts %}
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
      {% endblock %}
    </div>
    {% include 'inventory/confirm.html' %}
    {% include 'inventory/footer.html' %}
  </body>
</html>

inventory/templates/inventory/confirm.html
<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="Are You Sure?" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                Delete?
            </div>
            <div class="modal-body">
                Are you really sure you want to delete this record?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <a class="btn btn-danger btn-ok">Delete</a>
            </div>
        </div>
    </div>
</div>

<script>
    $('#confirm-delete').on('show.bs.modal', function(e) {
        $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
    });
</script>

inventory/templates/inventory/footer.html
<footer>
  <p id="footer-text">&copy; 2016 Ryan Palo for ProtoQuick, Inc.</p>
</footer>

inventory/templates/inventory/header.html
<header>
  <p id="logo">ProtoQuick Plastics</p>
  <nav class="text-center">
    <ul class="nav nav-pills nav-justified">
      <li {% if active_tab == 'plastic-home' %}class="active" {% endif %} role="presentation"><a href="{% url 'plastic-home' %}">Plastics Home</a></li>
      <li {% if active_tab == 'plastic-new' %}class="active" {% endif %} role="presentation"><a href="{% url 'add' %}">New Plastic</a></li>
      <li {% if active_tab == 'log-new' %}class="active" {% endif %} role="presentation"><a href="{% url 'add-log' %}">Make a Change</a></li>
      <li {% if active_tab == 'log-home' %}class="active" {% endif %} role="presentation"><a href="{% url 'log-home' %}">All Logs</a></li>
    </ul>
  </nav>
</header>

inventory/templates/inventory/index.html
{% extends 'inventory/base.html' %}

{% block title %}PQ Inventory - Plastics{% endblock %}

{% block body %}
{% include 'inventory/header.html' with active_tab='plastic-home' %}
<div class="container">
  <h2>Plastics</h2>
  <form class="form-inline searchForm" action="{% url 'plastic-home' %}" method="get">
    <div class="input-group">
      <input class="form-control" type="text" name="search" value="{{ search }}" placeholder="Search">
      <div class="input-group-btn">
        <button class="btn btn-default" type="submit">
          <i class="glyphicon glyphicon-search"></i>
        </button>
      </div>
      <div class="input-group-btn">
        <button class="btn btn-default" type="button" onClick="submitBlank();">
          <i class="glyphicon glyphicon-remove"></i>
        </button>
      </div>
    </div>
  </form>
  <table class="table table-hover text-center">
    <tr>
      <th>#</th>
      <th>Plastic Number</th>
      <th>Description</th>
      <th>Quantity (lbs)</th>
      <th>Vendor</th>
      <th>Remove</th>
    </tr>
    {% for plastic in plastics %}
      <tr {% if plastic.needs_ordered %}class="danger"{% endif %}>
        <td>{{ plastic.id }}</td>
        <td><a href="{{ plastic.get_absolute_url }}">{{ plastic.number }}</a></td>
        <td>{{ plastic.description }}</td>
        <td>{{ plastic.quantity }}</td>
        <td>{{ plastic.vendor }}</td>
        <td><a class="deleter" data-href="{% url 'delete' plastic.pk %}" data-toggle="modal" data-target="#confirm-delete"><span class="glyphicon glyphicon-remove"></span></a></td>
      </tr>
    {% endfor %}
  </table>
</div>
<script>
  function submitBlank() {
    const searchForm = document.querySelector(".searchForm");
    const searchText = searchForm.querySelector('input[name="search"]');
    searchText.value = "";
    window.location = "./";
    return false;
  }
</script>
{% endblock %}

inventory/templates/inventory/log-form.html
{% extends 'inventory/base.html' %}
{% load helpers %}

{% block title %}
Add Plastic
{% endblock %}

{% block body %}
{% include 'inventory/header.html' with active_tab='log-new' %}
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h2>New Log</h2>
      {% include 'inventory/form-errors.html' %}
      <form action="{% url 'add-log' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
          <div class="form-group">
            {{ field.errors }}
            {{ field.label_tag }}{% if field.field.required %}*{% endif %} {{ field|addClass:'form-control' }}
          </div>
        {% endfor %}
        <input type="submit" value="Save" />
      </form>
    </div>
  </div>
{% endblock %}

inventory/templates/inventory/log-home.html
{% extends 'inventory/base.html' %}

{% block title %}PQ Inventory - Logs{% endblock %}

{% block body %}
{% include 'inventory/header.html' with active_tab='log-home' %}
<div class="container">
  <h1>Logs{% if plastic %} for {{ plastic.number }}{% endif %}</h1>
  <table class="table table-striped text-center">
    <tr>
      <th>#</th>
      <th>Timestamp</th>
      <th>Plastic</th>
      <th>New Value (lbs)</th>
      <th>Notes</th>
      <th>Remove</th>
    </tr>
    {% for log in logs %}
      <tr>
        <td>{{ log.id }}</td>
        <td>{{ log.timestamp }}</a></td>
        <td>{{ log.plastic }}</td>
        <td>{{ log.new_value }}</td>
        <td>{{ log.notes }}</td>
        <td><a class="deleter" data-href="{% url 'delete-log' log.pk %}" data-toggle="modal" data-target="#confirm-delete"><span class="glyphicon glyphicon-remove"></span></a></td>
      </tr>
    {% endfor %}
  </table>
</div>
<script>
  const header = document.querySelector(".nav-pills");
  const plasticHome = header.firstElementChild;
  const logHome = header.lastElementChild;
  plasticHome.classList.remove("active");
  logHome.classList.add("active");
</script>
{% endblock %}

inventory/templates/inventory/plastic-form.html
{% extends 'inventory/base.html' %}
{% load helpers %}

{% block title %}
{% if plastic %}{{ plastic.number }}{% else %}Add Plastic{% endif %}
{% endblock %}

{% block body %}
{% include 'inventory/header.html' with active_tab='plastic-new' %}
  <div class="row">
    <div class="col-md-9 main">
      <h2{% if plastic and plastic.needs_ordered %} class="text-danger"{% endif %}>
        {% if plastic %}
          {{ plastic.number }}
        {% else %}
          New Plastic
        {% endif %}
      </h2>
      {% include 'inventory/form-errors.html' %}
      <form action="{% if plastic %}{{ plastic.get_absolute_url }}{% else %}{% url 'add' %}{% endif %}" method="post">
        {% csrf_token %}
        {% for field in form %}
          <div class="form-group">
            {{ field.errors }}
            {{ field.label_tag }}{% if field.field.required %}*{% endif %} {{ field|addClass:'form-control' }}
          </div>
        {% endfor %}
        <input type="submit" value="Save" />
      </form>
    </div>
  <br>
  {% if plastic %}
  <div class="row">
    <div class="col-md-9 text-center">
      <table class="table striped-table">
        <tr>
          <th>#</th>
          <th>Timestamp</th>
          <th>New Value (lbs)</th>
          <th>Notes</th>
          <th>Remove</th>
        </tr>
        {% for log in plastic.log_set.all %}
        <tr>
          <td>{{ log.pk }}</td>
          <td>{{ log.timestamp }}</td>
          <td>{{ log.new_value }}</td>
          <td>{{ log.notes }}</td>
          <td><a class="deleter" data-href="{% url 'delete-log' log.pk %}" data-toggle="modal" data-target="#confirm-delete"><span class="glyphicon glyphicon-remove"></span></a></td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>
  {% endif %}
{% endblock %}